### PR TITLE
[CI] split for xt subdirs

### PR DESCRIPTION
**Pull request by renefritze**
with this PR Azure will now only create `subdir times images` many parallel builds. Each build will call `${subdir}_test_binaries` and execute all tests with the label `${subdir}`.

I'm getting lapack link errors now though: https://dev.azure.com/dune-community/dune-xt/_build/results?buildId=1004&view=logs&j=8e3ede11-9f7c-5727-0031-e953d5f21483
Do those maybe ring a bell @tobiasleibner ?

This does not yet split bindings/python tests.

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Yes, the linking errors should be fixed by https://github.com/dune-community/dune-xt/pull/10/commits/9d54d015d30ef0d59395c6caafac200544502f87.

**Comment by tobiasleibner** [comment]
Maybe you will also need https://github.com/dune-community/dune-xt/pull/10/commits/9a80334c4d5dd613eebfa55f123b0298ab44ba30 to fix more linking errors.

**Comment by renefritze** [comment]
Thanks! 
Checking now: #18

**Comment by tobiasleibner** [comment]
Closing in favor of #18.

**Pull request closed without merging**
